# Generated by Django 5.2.5 on 2025-10-18 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Work Progress'),
        ),
    ]
