# Generated by Django 5.2.5 on 2025-10-31 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_project_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='images',
            field=models.ImageField(default=True, upload_to=''),
            preserve_default=False,
        ),
    ]
